### ISSUE TITLE
可以制作帮助文档吗？

### ISSUE THREAD

**Issue by wuwo020** [tediorelee/koishi-plugin-twitter-images-videos#1]
可以为此插件做一个说明文档吗？不太清楚这个插件应该如何使用

**Comment by tediorelee** [comment]
需要一个twitter开发者的apikey填进去就好，会自动识别群聊的twitter post链接并解析图片内容等

**Comment by wuwo020** [comment]
嗷好的，已经再申请了。他们审核相当慢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 晚上7:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1)




 
需要一个twitter开发者的apikey填进去就好，会自动识别群聊的twitter post链接并解析图片内容等

**Comment by tediorelee** [comment]
是的，推特API不像Google那样简单（捂脸

**Comment by tediorelee** [comment]
> 嗷好的，已经再申请了。他们审核相当慢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月11日(周日) 晚上7:37 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1) 需要一个twitter开发者的apikey填进去就好，会自动识别群聊的twitter post链接并解析图片内容等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

等等，我看了一下我现在API用的是1.1，Bearer token的形式，有点老了，没有迁移到新的V2 API，如果确认想要用这个插件的话，私发我邮件我给你我的token吧反正基本不会过期
后面有时间我把这个迁移到v2的api

**Comment by wuwo020** [comment]
***@***.***（我还不会在GitHub上私信）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 晚上7:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1)




  
嗷好的，已经再申请了。他们审核相当慢
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月11日(周日) 晚上7:37 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1) 需要一个twitter开发者的apikey填进去就好，会自动识别群聊的twitter post链接并解析图片内容等 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
等等，我看了一下我现在API用的是1.1，Bearer token的形式，有点老了，没有迁移到新的V2 API，如果确认想要用这个插件的话，私发我邮件我给你我的token吧反正基本不会过期
 后面有时间我把这个迁移到v2的api

**Comment by tediorelee** [comment]
直接发出来会被屏蔽掉，你点开我的主页上有我的邮箱

**Comment by wuwo020** [comment]
我我我，我应该发送了消息。。。我不确定是否有接受到，咳咳咳，感谢感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 晚上7:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1)




 
直接发出来会被屏蔽掉，你点开我的主页上有我的邮箱

**Comment by tediorelee** [comment]
给你回复了哦，看看垃圾邮件分组，你发我的也进了垃圾邮件不知道为什么

**Comment by wuwo020** [comment]
好的，垃圾邮件内找到了，感谢回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tediorelee/koishi-plugin-twitter-images-videos] 可以制作帮助文档吗？ (Issue #1)




 
给你回复了哦，看看垃圾邮件分组，你发我的也进了垃圾邮件不知道为什么
